# Tensor Calculus

Tensors are fundamental mathematical constructs in fields such as physics and engineering. Historically however, tensors have made fewer inroads in computer science, which has traditionally been more associated with discrete mathematics and logic. This state of affairs has started to change significantly with the advent of machine learning.

Modern machine learning is founded upon the manipulation of tensors and the calculus of tensors.

To start, we will give some simple examples of tensors that readers will likely be familiar with. The simplest example of a tensor is a scalar, a single constant value drawn from the real numbers (Recall that the real numbers are decimal numbers of arbitrary precision, with both positive and negative numbers permitted). Mathematically, we
denote the real numbers by the ℝ. More formally, we call a scalar a **0-tensor**, a vector a **1-tensor**, and a matrix a **2-tensor**. In data analysis, we represent multiarray datasets as tensors and we can manipulate them using libraries such as **TensorFlow**, **PyTorch** and **Keras**. To save us the mathematical rigor, we're only going to learn how to use tensors using said libraries and cover the mathematics in a cursory manner.

Let's go ahead and start with the basics.

In [3]:
import numpy as np
import tensorflow as tf

In [4]:
rank_1_tensor = tf.constant([[2.0, 3.0, 4.0]], dtype=tf.float32)
rank_2_tensor = tf.constant([[1, 2],
                             [3, 4],
                             [5, 6]], dtype=tf.float16)
rank_3_tensor = tf.constant([
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9]],
  [[10, 11, 12, 13, 14],
   [15, 16, 17, 18, 19]],
  [[20, 21, 22, 23, 24],
   [25, 26, 27, 28, 29]],])

print(rank_1_tensor); print(rank_2_tensor); print(rank_3_tensor)

tf.Tensor([[2. 3. 4.]], shape=(1, 3), dtype=float32)
tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float16)
tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


# Sparse Tensors

A sparse tensor is a multi-dimensional array (tensor) in which the vast majority of elements are zero. Instead of storing every single element—which wastes massive amounts of memory and processing power—sparse tensors are optimized to store only the non-zero values and their coordinate locations.

When working with tensors that contain a lot of zero values, it is important to store them in a space- and time-efficient manner. Sparse tensors enable efficient storage and processing of tensors that contain a lot of zero values. Sparse tensors are used extensively in encoding schemes like TF-IDF as part of data pre-processing in NLP applications and for pre-processing images with a lot of dark pixels in computer vision applications.

Let's generate a sparse tensor now.

In [5]:
# Sparse tensors store values by index in a memory-efficient manner
sparse_tensor = tf.sparse.SparseTensor(indices=[[0, 0], [1, 2]],
                                       values=[1, 2],
                                       dense_shape=[3, 4])
print(sparse_tensor, "\n")

# You can convert sparse tensors to dense
print(tf.sparse.to_dense(sparse_tensor))

SparseTensor(indices=tf.Tensor(
[[0 0]
 [1 2]], shape=(2, 2), dtype=int64), values=tf.Tensor([1 2], shape=(2,), dtype=int32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64)) 

tf.Tensor(
[[1 0 0 0]
 [0 0 2 0]
 [0 0 0 0]], shape=(3, 4), dtype=int32)
